"""empty message

Revision ID: 2d448d6e4dd6
Revises: 
Create Date: 2019-10-14 22:46:09.182047

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d448d6e4dd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index('subappididx', table_name='instance')
    op.drop_column('instance', 'instancetype')
    op.alter_column('subapp', 'appid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('subapp', 'createdAt',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('subapp', 'subappurl',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.alter_column('subapp', 'updatedAt',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_subapp_subappsid'), 'subapp', ['subappsid'], unique=False)
    op.drop_index('appididx', table_name='subapp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('appididx', 'subapp', ['appid'], unique=False)
    op.drop_index(op.f('ix_subapp_subappsid'), table_name='subapp')
    op.alter_column('subapp', 'updatedAt',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('subapp', 'subappurl',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.alter_column('subapp', 'createdAt',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('subapp', 'appid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('instance', sa.Column('instancetype', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=False))
    op.create_index('subappididx', 'instance', ['subappid'], unique=False)
    op.create_table('user',
    sa.Column('uid', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('auth', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=3), server_default=sa.text("'0'"), nullable=True),
    sa.Column('domain', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('isverified', mysql.INTEGER(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('wx_openid', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('createdAt', mysql.DATETIME(), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
