"""empty message

Revision ID: 9ced3f735388
Revises: 
Create Date: 2020-03-04 01:39:58.200369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Date, DATETIME
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '9ced3f735388'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    # Create an ad-hoc table to use for the insert statement.
    user_table = table('user', column('uid', Integer),
                       column('username', String), column('password', String),
                       column('userdomain', String),
                       column('createdAt', DATETIME),
                       column('updatedAt', DATETIME))
    op.bulk_insert(user_table, [
        {
            'uid': 1,
            'username': 'admin',
            'password': 'admin',
            'userdomain': 'xxx.com',
            'createdAt': datetime.now(),
            'updatedAt': datetime.now(),
        },
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.alter_column('user',
                    'updatedAt',
                    existing_type=mysql.DATETIME(),
                    nullable=False)
    op.alter_column('user',
                    'createdAt',
                    existing_type=mysql.DATETIME(),
                    nullable=False)
    op.create_index('subappsid', 'subapp', ['subappsid'], unique=True)
    op.drop_index(op.f('ix_subapp_subappsid'), table_name='subapp')
    op.alter_column('subapp',
                    'updatedAt',
                    existing_type=mysql.DATETIME(),
                    nullable=False)
    op.alter_column('subapp',
                    'createdAt',
                    existing_type=mysql.DATETIME(),
                    nullable=False)
    op.drop_constraint(None, 'saplogin', type_='foreignkey')
    op.create_index('subappididx', 'saplogin', ['subappid'], unique=False)
    op.create_index('subappididx', 'instance', ['subappid'], unique=False)
    # ### end Alembic commands ###
