"""empty message

Revision ID: e686fa212efa
Revises: 
Create Date: 2020-03-04 03:59:30.560449

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import mysql
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Date, DATETIME
from datetime import datetime

# revision identifiers, used by Alembic.
revision = 'e686fa212efa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'app',
        sa.Column('appid',
                  sa.Integer(),
                  autoincrement=True,
                  nullable=False,
                  comment='app id'),
        sa.Column('appname',
                  sa.String(length=50),
                  nullable=False,
                  comment='app name'),
        sa.Column('appdesc',
                  sa.String(length=100),
                  nullable=False,
                  comment='app description'),
        sa.Column('appdomain',
                  sa.String(length=100),
                  nullable=False,
                  comment='app domain name'),
        sa.Column('createdAt',
                  sa.DateTime(),
                  nullable=True,
                  comment='app create datetime'),
        sa.Column('updatedAt',
                  sa.DateTime(),
                  nullable=True,
                  comment='app update datetime'),
        sa.PrimaryKeyConstraint('appid'))
    op.create_index(op.f('ix_app_appname'), 'app', ['appname'], unique=False)
    op.create_table(
        'host',
        sa.Column('hostid',
                  sa.Integer(),
                  autoincrement=True,
                  nullable=False,
                  comment='host unique id'),
        sa.Column('hostname',
                  sa.String(length=10),
                  nullable=False,
                  comment='hostname'),
        sa.Column('hostdomain',
                  sa.String(length=100),
                  nullable=True,
                  comment='host domain name'),
        sa.Column('ipaddress',
                  sa.String(length=255),
                  nullable=False,
                  comment='ip address'),
        sa.Column('cpu', sa.Integer(), nullable=False, comment='cpu'),
        sa.Column('memory', sa.BigInteger(), nullable=False, comment='memory'),
        sa.Column('fsmount',
                  sa.TEXT(),
                  nullable=True,
                  comment='file system mount'),
        sa.Column('createdAt',
                  sa.DateTime(),
                  nullable=True,
                  comment='host create datetime'),
        sa.Column('updatedAt',
                  sa.DateTime(),
                  nullable=True,
                  comment='host update datetime'),
        sa.PrimaryKeyConstraint('hostid'))
    op.create_index(op.f('ix_host_hostname'),
                    'host', ['hostname'],
                    unique=False)
    op.create_table(
        'subapp',
        sa.Column('subappid',
                  sa.Integer(),
                  autoincrement=True,
                  nullable=False,
                  comment='subapp id'),
        sa.Column('subappsid',
                  sa.String(length=5),
                  nullable=False,
                  comment='subapp SID'),
        sa.Column('subappurl',
                  sa.String(length=100),
                  nullable=True,
                  comment='subapp url'),
        sa.Column('subappdesc',
                  sa.String(length=100),
                  nullable=True,
                  comment='subapp description'),
        sa.Column('createdAt',
                  sa.DateTime(),
                  nullable=True,
                  comment='subapp create datetime'),
        sa.Column('updatedAt',
                  sa.DateTime(),
                  nullable=True,
                  comment='subapp update datetime'),
        sa.PrimaryKeyConstraint('subappid'))
    op.create_index(op.f('ix_subapp_subappsid'),
                    'subapp', ['subappsid'],
                    unique=False)
    op.create_table(
        'user',
        sa.Column('uid',
                  sa.Integer(),
                  autoincrement=True,
                  nullable=False,
                  comment='user unique id'),
        sa.Column('username',
                  sa.String(length=50),
                  nullable=False,
                  comment='user name'),
        sa.Column('password',
                  sa.String(length=100),
                  nullable=False,
                  comment='user password'),
        sa.Column('userdomain',
                  sa.String(length=100),
                  nullable=False,
                  comment='user domain name'),
        sa.Column('createdAt',
                  sa.DateTime(),
                  nullable=True,
                  comment='user create datetime'),
        sa.Column('updatedAt',
                  sa.DateTime(),
                  nullable=True,
                  comment='user update datetime'),
        sa.PrimaryKeyConstraint('uid'))
    op.create_index(op.f('ix_user_username'),
                    'user', ['username'],
                    unique=False)
    op.create_table(
        'instance',
        sa.Column('instid',
                  sa.Integer(),
                  autoincrement=True,
                  nullable=False,
                  comment='instance unique id'),
        sa.Column('instanceid',
                  sa.String(length=20),
                  nullable=False,
                  comment='instance id'),
        sa.Column('subappid', sa.Integer(), nullable=True),
        sa.Column('hostid', sa.Integer(), nullable=True),
        sa.Column('instanceno',
                  sa.String(length=5),
                  nullable=False,
                  comment='instance number'),
        sa.Column('instancetype',
                  sa.String(length=10),
                  nullable=False,
                  comment='instance type'),
        sa.Column('createdAt',
                  sa.DateTime(),
                  nullable=True,
                  comment='instance create datetime'),
        sa.Column('updatedAt',
                  sa.DateTime(),
                  nullable=True,
                  comment='instance update datetime'),
        sa.ForeignKeyConstraint(
            ['hostid'],
            ['host.hostid'],
        ), sa.ForeignKeyConstraint(
            ['subappid'],
            ['subapp.subappid'],
        ), sa.PrimaryKeyConstraint('instid'))
    op.create_index(op.f('ix_instance_instanceid'),
                    'instance', ['instanceid'],
                    unique=False)
    op.create_table(
        'saplogin',
        sa.Column('loginid',
                  sa.Integer(),
                  autoincrement=True,
                  nullable=False,
                  comment='login unique id'),
        sa.Column('subappid', sa.Integer(), nullable=True),
        sa.Column('username',
                  sa.String(length=50),
                  nullable=False,
                  comment='username'),
        sa.Column('password',
                  sa.String(length=50),
                  nullable=False,
                  comment='password'),
        sa.Column('client',
                  sa.String(length=5),
                  nullable=False,
                  comment='client number'),
        sa.Column('createdAt',
                  sa.DateTime(),
                  nullable=True,
                  comment='instance create datetime'),
        sa.Column('updatedAt',
                  sa.DateTime(),
                  nullable=True,
                  comment='instance update datetime'),
        sa.ForeignKeyConstraint(
            ['subappid'],
            ['subapp.subappid'],
        ), sa.PrimaryKeyConstraint('loginid'))
    # ### end Alembic commands ###

    # Create an ad-hoc table to use for the insert statement.
    user_table = table('user', column('uid', Integer),
                       column('username', String), column('password', String),
                       column('userdomain', String),
                       column('createdAt', DATETIME),
                       column('updatedAt', DATETIME))
    op.bulk_insert(user_table, [
        {
            'uid': 1,
            'username': 'admin',
            'password': 'admin',
            'userdomain': 'xxx.com',
            'createdAt': datetime.now(),
            'updatedAt': datetime.now(),
        },
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saplogin')
    op.drop_index(op.f('ix_instance_instanceid'), table_name='instance')
    op.drop_table('instance')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_subapp_subappsid'), table_name='subapp')
    op.drop_table('subapp')
    op.drop_index(op.f('ix_host_hostname'), table_name='host')
    op.drop_table('host')
    op.drop_index(op.f('ix_app_appname'), table_name='app')
    op.drop_table('app')
    # ### end Alembic commands ###
